(function () {
  var tool = document.body.dataset.toolReport;
  if (!tool) return;
  var isBackground = tool === "Background Changer";
  var css = '.tool-report-trigger{display:block;width:100%;margin:10px 0 0;padding:11px 16px;border:1px solid #ff7182;border-radius:11px;background:#241c29;color:#fff;font:800 13px sans-serif;cursor:pointer}.tool-report-trigger:hover{background:#382031}.tool-report-overlay{position:fixed;inset:0;z-index:9999;display:grid;place-items:center;padding:20px;background:rgba(3,7,15,.72);backdrop-filter:blur(10px)}.tool-report-modal{width:min(100%,520px);padding:26px;border:1px solid rgba(255,130,150,.35);border-radius:22px;background:linear-gradient(145deg,#18243b,#170e1b);color:#fff;font-family:sans-serif}.tool-report-modal label{display:grid;gap:7px;margin:14px 0;font-weight:800;font-size:13px}.tool-report-modal input,.tool-report-modal select,.tool-report-modal textarea{width:100%;padding:12px;border:1px solid #46587b;border-radius:10px;background:#0f1726;color:#fff;font:inherit}.tool-report-modal textarea{min-height:105px}.tool-report-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.tool-report-actions button{padding:11px 15px;border:0;border-radius:10px;font-weight:900;cursor:pointer}.tool-report-submit{background:#ff394b;color:#fff}';
  document.head.insertAdjacentHTML('beforeend','<style>'+css+'</style>');
  var trigger = document.createElement('button');
  trigger.className = 'tool-report-trigger'; trigger.type = 'button'; trigger.textContent = 'Report a problem';
  var primary = document.querySelector('#ugcButton,#templateButton,#downloadButton,#fetchButton,#audioButton,#processBtn,#generateButton');
  if (primary) primary.insertAdjacentElement('afterend', trigger); else document.querySelector('main').appendChild(trigger);
  trigger.onclick = async function () {
    var auth = await fetch('/auth/me',{credentials:'include'}).catch(function(){return null});
    if (!auth || !auth.ok) { alert('Log in or sign up before submitting a report.'); return; }
    var urlField = isBackground ? '' : '<label id="toolReportUrl">Roblox item URL (required)<input id="toolReportItemUrl" type="url" placeholder="https://www.roblox.com/catalog/..." required></label>';
    document.body.insertAdjacentHTML('beforeend','<div class="tool-report-overlay"><form class="tool-report-modal"><h2>Report '+tool+'</h2><p>Reports are sent to Community Bug Reports.</p><label>Reason<select id="toolReportReason"><option value="download">Downloadable Content</option><option value="other">Other</option></select></label>'+urlField+'<label>Additional information<textarea id="toolReportDetails" required placeholder="Describe what happened and what you expected."></textarea></label><label>Attachment (optional)<input id="toolReportAttachment" type="file" accept="image/*,.txt"></label><div class="tool-report-actions"><button type="button" class="tool-report-cancel">Cancel</button><button class="tool-report-submit">Send report</button></div></form></div>');
    var overlay=document.querySelector('.tool-report-overlay'), reason=document.getElementById('toolReportReason'), url=document.getElementById('toolReportUrl'); reason.onchange=function(){url.hidden=reason.value==='other'}; overlay.querySelector('.tool-report-cancel').onclick=function(){overlay.remove()}; overlay.querySelector('form').onsubmit=async function(e){e.preventDefault();var link=document.getElementById('toolReportItemUrl');if(!isBackground&&reason.value==='download'&&(!link||!link.value))return;var file=document.getElementById('toolReportAttachment').files[0];var body=['Tool: '+tool,'Reason: '+reason.value,(link&&link.value?'Roblox URL: '+link.value:''),'Details: '+document.getElementById('toolReportDetails').value,(file?'Attachment supplied: '+file.name:'')].filter(Boolean).join('\n');var r=await fetch('/api/community-posts/bug-reports',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:tool+' report',body:body})});if(!r.ok){alert((await r.json().catch(function(){return{}})).error||'Could not send report.');return}overlay.remove();alert('Report sent to Community Bug Reports.');};
  };
}());
