(function () {
  var tool = document.body.dataset.toolReport;
  if (!tool) return;
  var isBackground = tool === "Background Changer";
  var css = '.tool-report-trigger{display:block;width:100%;margin:10px 0 0;padding:11px 16px;border:1px solid #ff7182;border-radius:11px;background:#241c29;color:#fff;font:800 13px sans-serif;cursor:pointer}.tool-report-trigger:hover{background:#382031}.rblx-cleaner-actions+.tool-report-trigger{margin-top:12px}.tool-report-overlay{position:fixed;inset:0;z-index:9999;display:grid;place-items:center;padding:20px;background:rgba(3,7,15,.72);backdrop-filter:blur(10px)}.tool-report-modal{width:min(100%,520px);padding:26px;border:1px solid rgba(255,130,150,.35);border-radius:22px;background:linear-gradient(145deg,#18243b,#170e1b);color:#fff;font-family:sans-serif}.tool-report-modal label{display:grid;gap:7px;margin:14px 0;font-weight:800;font-size:13px}.tool-report-modal label[hidden]{display:none}.tool-report-modal input,.tool-report-modal select,.tool-report-modal textarea{width:100%;padding:12px;border:1px solid #46587b;border-radius:10px;background:#0f1726;color:#fff;font:inherit}.tool-report-modal textarea{min-height:105px}.tool-report-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.tool-report-actions button{padding:11px 15px;border:0;border-radius:10px;font-weight:900;cursor:pointer}.tool-report-submit{background:#ff394b;color:#fff}';
  document.head.insertAdjacentHTML('beforeend','<style>'+css+'</style>');
  var trigger = document.createElement('button');
  trigger.className = 'tool-report-trigger'; trigger.type = 'button'; trigger.textContent = 'Report a problem';
  var primary = document.querySelector('#ugcButton,#templateButton,#downloadButton,#fetchButton,#audioButton,#processBtn,#generateButton');
  var backgroundActions = document.querySelector('.rblx-cleaner-actions');
  if (backgroundActions) backgroundActions.insertAdjacentElement('afterend', trigger); else if (primary) primary.insertAdjacentElement('afterend', trigger); else document.querySelector('main').appendChild(trigger);
  trigger.onclick = async function () {
    var cachedUser = null;
    try { cachedUser = JSON.parse(localStorage.getItem('rblxtools_auth_user') || 'null'); } catch (_error) {}
    if (!cachedUser) { alert('Log in or sign up before submitting a report.'); return; }
    var urlField = isBackground ? '' : '<label id="toolReportUrl">Roblox item URL (required)<input id="toolReportItemUrl" type="url" placeholder="https://www.roblox.com/catalog/..." required></label>';
    document.body.insertAdjacentHTML('beforeend','<div class="tool-report-overlay"><form class="tool-report-modal"><h2>Report '+tool+'</h2><p>Reports are sent to Community Bug Reports.</p><label>Reason<select id="toolReportReason"><option value="download">Downloadable Content</option><option value="other">Other</option></select></label>'+urlField+'<label>Please further explain your issue<textarea id="toolReportDetails" required placeholder="Tell us what happened and what you expected."></textarea></label><label>Attachment (optional)<input id="toolReportAttachment" type="file" accept="image/*,.txt"></label><div class="tool-report-actions"><button type="button" class="tool-report-cancel">Cancel</button><button class="tool-report-submit">Send report</button></div></form></div>');
    var overlay=document.querySelector('.tool-report-overlay'), reason=document.getElementById('toolReportReason'), url=document.getElementById('toolReportUrl'), link=document.getElementById('toolReportItemUrl');
    reason.onchange=function(){var needsUrl=reason.value==='download'; if(url) url.hidden=!needsUrl; if(link) link.required=needsUrl;};
    overlay.querySelector('.tool-report-cancel').onclick=function(){overlay.remove()};
    overlay.querySelector('form').onsubmit=async function(e){e.preventDefault();var file=document.getElementById('toolReportAttachment').files[0];var body=[(link&&link.value?'Roblox URL: '+link.value:''),'Details: '+document.getElementById('toolReportDetails').value,(file?'Attachment supplied: '+file.name:'')].filter(Boolean).join('\n\n');var submit=overlay.querySelector('.tool-report-submit');submit.disabled=true;var r=await fetch('/api/community-posts/bug-reports',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:tool+' report',body:body})});if(!r.ok){submit.disabled=false;alert((await r.json().catch(function(){return{}})).error||'Could not send report.');return}overlay.querySelector('.tool-report-modal').innerHTML='<h2>Thank you</h2><p>Your report has been sent to Community Bug Reports. Our team will look into it.</p><div class="tool-report-actions"><button type="button" class="tool-report-submit">OK</button></div>';overlay.querySelector('.tool-report-submit').onclick=function(){overlay.remove()};};
  };
}());
